language: go
go:
- 1.11.x
- master
matrix:
  fast_finish: true
  allow_failures:
  - go: master
env:
  global:
  - DEP_VERSION="0.5.0"
  matrix:
  - GIMME_OS=linux GIMME_ARCH=amd64
addons:
  apt:
    packages:
    - libcryptsetup-dev
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o ${GOPATH}/bin/dep
- chmod +x ${GOPATH}/bin/dep
install:
- dep ensure
script:
- diff -u <(echo -n) <(gofmt -d .)
- go test -v -x -ldflags "-X main.VERSION=${TRAVIS_TAG}"
before_deploy:
- mkdir -p tmp/luks2crypt
- cp luks2crypt README.md COPYING LICENSE tmp/luks2crypt/
- tar -C tmp -czvf luks2crypt-${TRAVIS_TAG}-${GIMME_OS}-${GIMME_ARCH}.tar.gz luks2crypt
jobs:
  include:
  - stage: build
    go: 1.11.x
    script: go build -v -ldflags "-X main.VERSION=${TRAVIS_TAG}"
    deploy:
      provider: releases
      file: luks2crypt-${TRAVIS_TAG}-${GIMME_OS}-${GIMME_ARCH}.tar.gz
      api_key:
        secure: Le6DJgkY2iAiibFia6YIEIBXRXpEiexemW0tw4jwxo1q0KVREAMb3+tGLEJr/lcEncNVV3DXbQUtEJRwfT/J/NbZXc9+UkOPvgrwX7qP67w4COzM0C/ibm5r+kcCc1xqTk12rxenS3JSulkEz60nQniT2HmZBwQT+2T1LudY+qCKQYA/ceGhgX4F+9rU6LMGH8t3jbT4QRf5woz7Suk7wLzLde+dS2M3fPHn716Y/mjYIaFIJH0EGSr/eWSrG9t50umwscaRZKEyWJJbL4BMl3ES1w3cPhKydM7+y+HcIEnzxlOstCfqxPQnAg6fdcCFNUHFrqVZn3GM5lj1Y7sLLDeuC9D919UoHMAGVydzbkoC0qKPL4hB217IY0rSoV8z0KuEDdQXC9AnMNfBUg+lhCvt7t+XBdf+w4QbjIzP+5YzAbusEXFtCBtSLdc8c7GsGKBtsN7wxpd5ZD6LdotSyzQ3Dj/ca9/2nJPp5IAZhCFk8Jpp3Xl+pGRx12xm7nNnG42OZshxrgl/+rlKnytoxujeZ6crw3iuoJhMVHDJNK1XuNTspdnOL4oDfyoVs4H++qFjx0EocW6YP3GQSQKFqP0QuooRwgZY3C1n/8HWLfTysXMIGqa24URlQ+litbNHJ07YDnFZk+TlUybtVfY+8g4KcRtC3tF9Fq2+PI7fWpU=
      skip_cleanup: true
      on:
        tags: true
